CREATE DATABASE IF NOT EXISTS dbGreenHouse;
USE dbGreenHouse;

-- USER
CREATE TABLE tbUser (
    idUser INT PRIMARY KEY AUTO_INCREMENT,
    nomeUser VARCHAR(60) NOT NULL,
    emailUser VARCHAR(60) NOT NULL,
    cpfUser CHAR(11) NOT NULL UNIQUE,
    senhaUser VARCHAR(32) NOT NULL
);